# RealmGateway Configuration Parameters

DEFAULT:
    name: gwa.demo

DNS:
    soa:
        - gwa.demo.
        - 0.168.192.in-addr.arpa.
        - 1.64.100.in-addr.arpa.
    ddnsserver:
        - [127.0.0.2, 53]
    proxylan:
        - [192.168.0.1, 53]
    proxylocal:
        - [127.0.0.1, 53]
    server:
        - [100.64.1.130, 53]
    resolver:
        - [8.8.8.8, 53]
    timeouts:
        naptr: [0.010, 0.100, 0.200]
        a:     [0.010, 0.100, 0.200]
        aaaa:  [0.010, 0.100, 0.200]
        any:   [0]

NETWORK:
#    namepool:
#        servicedomain:
#            - www
#            - sip
    addresspool:
        servicepool:
            - 100.64.1.130/32
        circularpool:
            - 100.64.1.133/32
            - 100.64.1.134/32
            - 100.64.1.135/32
    iptables:
        circularpool:
            nfqueue: 1
            chain: NAT_PRE_CPOOL
        hostpolicy:
            chain: FILTER_HOST_POLICY
            accept: FILTER_HOST_POLICY_ACCEPT

DATAREPOSITORY:
    subscriberdata: gwa.demo.datarepository.yaml
    servicedata: gwa.demo.datarepository.yaml
    policydata: gwa.demo.datarepository.yaml
