# CES Configuration Parameters

CESParameters:
    name: cesa
    cesid: cesa.lte.
    CETPVersion: 2
    certificate: config_cesa/cesa.crt
    private_key: config_cesa/cesa.key
    ca_certificate: config_cesa/ca.crt
    c2c_establishment_t0: 2
    incomplete_cetp_state_t0: 2
    max_c2c_transports: 3
    max_naptrs_per_sec: 400
    max_naptrs_per_dns: 5
    host_filtering_t0: 30
    dp_ttl: 3600
    keepalive_idle_t0: 5
    keepalive_count: 3
    keepalive_interval: 2
    caces: 127.0.0.1
    fw_version: 0.1
    pow_algo: hashcash
    ces_session_limit: 300
    host_sessions: 2
    max_ces_session_limit: 400
    max_dp_ttl: 7200
    max_host_ratelimit: 10
    min_keepalive_timeout: 10
    rloc_preference:
        - 100,80,ipv4,10.0.3.101,ISP
        - 100,60,ipv4,10.1.3.101,IXP
        - 100,40,ipv6,11:22:33:44:55:66:77:01,ICP
    payload_preference:
        ipsec:  100
        geneve: 80
        gre:    60
        vxlan:  40

CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 10.0.3.101
        port: 48001
        transport: tls
    server2:
        ip: 10.0.3.101
        port: 48002
        transport: tls
    server3:
        ip: 10.0.3.101
        port: 48003
        transport: tls

cetp_policy_file: config_cesa/cetp_policies.json
