# CES Configuration Parameters

CES Identification:
    name: cesa
    domainId: cesa.demo.lte.
    

DNS:
    soa: cesa.demo.lte.
    zonefile: db.cesa.demo.lte.
    server:
        loopback:
            ip: 127.0.0.1
            port: 53
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0

CETPServers:
    serverNames:
        - server1
        - server2
    server1:
        ip: 127.0.0.1
        port: 48001
        transport: tcp
    server2:
        ip: 127.0.0.1
        port: 48002
        transport: tcp

cetp_policy_file: config_cesa/cetp_policies.json