# CES Configuration Parameters

CESParameters:
    name: cesc
    cesid: cesc.demo.lte.
    certificate: config_cesc/cesc.crt
    private_key: config_cesc/cesc.key
    ca_certificate: config_cesc/ca.crt
    dp_ttl: 3600
    keepalive_timeout: 2
    keepalive_cycle: 10
    connection_expiry: 20
    caces: 127.0.0.1
    fw_version: 0.1
    ces_session_limit: 30
    host_ratelimit: 2
    pow_algo: hashcash
    max_ces_session_limit: 100
    max_dp_ttl: 7200
    max_host_ratelimit: 10
    min_keepalive_timeout: 10

DNS:
    soa: cesc.demo.lte.
    zonefile: db.cesc.demo.lte.
    server:
        loopback:
            ip: 127.0.0.1
            port: 55
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0
            
CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 10.0.3.105
        port: 49001
        transport: tcp
    server2:
        ip: 10.0.3.105
        port: 49002
        transport: tcp
    server3:
        ip: 10.1.3.105
        port: 49003
        transport: tls

cetp_policy_file: config_cesc/cetp_policies.json
