# CES Configuration Parameters

CESParameters:
    name: cese
    cesid: cese.lte.
    CETPVersion: 2
    certificate: config_ces_test/cese.crt
    private_key: config_ces_test/cese.key
    ca_certificate: config_ces_test/ca.crt
    c2c_establishment_t0: 2
    incomplete_cetp_state_t0: 2
    max_rces_transports: 5
    max_naptrs_per_sec: 400
    max_naptrs_per_dns: 5
    host_filtering_t0: 30
    keepalive_t0: 2
    dp_ttl: 3600
    keepalive_cycle: 150
    caces: 127.0.0.1
    fw_version: 0.1
    pow_algo: hashcash
    ces_session_limit: 300
    host_sessions: 2
    max_ces_session_limit: 400
    max_dp_ttl: 7200
    max_host_ratelimit: 10
    min_keepalive_timeout: 10
    
DNS:
    soa: cese.lte.
    zonefile: db.cese.lte.
    server:
        loopback:
            ip: 10.0.3.106
            port: 53
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0

CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 10.0.3.106
        port: 49001
        transport: tcp
    server2:
        ip: 10.0.3.106
        port: 49002
        transport: tcp
    server3:
        ip: 10.0.3.106
        port: 49003
        transport: tls

cetp_policy_file: config_ces_test/cetp_policies_cese.json
