# CES Configuration Parameters

CESParameters:
    name: cesb
    cesid: cesb.lte.
    CETPVersion: 2
    certificate: config_cesb/cesb.crt
    private_key: config_cesb/cesb.key
    ca_certificate: config_cesb/ca.crt
    c2c_establishment_t0: 2
    incomplete_cetp_state_t0: 2
    max_c2c_transports: 3
    max_naptrs_per_dns: 5
    max_naptrs_per_sec: 4000
    host_filtering_t0: 30
    dp_ttl: 3600
    keepalive_idle_t0: 5
    keepalive_interval: 2
    keepalive_count: 3
    caces: 127.0.0.1
    fw_version: 0.1
    pow_algo: hashcash
    ces_session_limit: 3000
    host_sessions: 2
    max_ces_session_limit: 4000
    max_dp_ttl: 7200
    max_host_ratelimit: 10
    min_keepalive_timeout: 10
    payload_preference:
        ipsec:  100
        geneve: 80
        gre:    60
        vxlan:  40

DNS:
    soa: cesb.lte.
    zonefile: db.cesb.lte.
    server:
        loopback:
            ip: 10.0.3.103
            port: 53
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0
            
CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 10.0.3.103
        port: 49001
        transport: tls
    server2:
        ip: 10.0.3.103
        port: 49002
        transport: tls
    server3:
        ip: 10.0.3.103
        port: 49003
        transport: tls

cetp_policy_file: config_cesb/cetp_policies.json
