# CES Configuration Parameters

CESParameters:
    name: cesb
    cesid: cesb.lte.
    certificate: config_cesb/cesb.crt
    private_key: config_cesb/cesb.key
    ca_certificate: config_cesb/ca.crt
    dp_ttl: 3600
    transport_establishment_t0: 2
    incomplete_cetp_state_t0: 2
    host_filtering_t0: 30
    keepalive_t0: 2
    keepalive_cycle: 30
    caces: 127.0.0.1
    fw_version: 0.1
    pow_algo: hashcash
    ces_session_limit: 30
    host_sessions: 2
    max_ces_session_limit: 100
    max_dp_ttl: 7200
    max_host_ratelimit: 10
    min_keepalive_timeout: 10

DNS:
    soa: cesb.lte.
    zonefile: db.cesb.lte.
    server:
        loopback:
            ip: 10.0.3.103
            port: 53
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0
            
CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 10.0.3.103
        port: 49001
        transport: tcp
    server2:
        ip: 10.0.3.103
        port: 49002
        transport: tcp
    server3:
        ip: 10.0.3.103
        port: 49003
        transport: tls

cetp_policy_file: config_cesb/cetp_policies.json
