# CES Configuration Parameters

CESParameters:
    name: cesb
    cesid: cesb.demo.lte.
    certificate: config_cesb/cesb.crt
    private_key: config_cesb/cesb.key
    ca_certificate: config_cesb/ca.crt
    dp_ttl: 3600
    keepalive_timeout: 2
    keepalive_cycle: 30
    max_c2c_negotiation_duration: 5
    connection_expiry: 150
    caces: 127.0.0.1
    fw_version: 0.1
    ces_session_limit: 30
    host_ratelimit: 2
    pow_algo: hashcash
    max_ces_session_limit: 100
    max_dp_ttl: 7200
    max_host_ratelimit: 10
    min_keepalive_timeout: 10

DNS:
    soa: cesb.demo.lte.
    zonefile: db.cesb.demo.lte.
    server:
        loopback:
            ip: 127.0.0.1
            port: 54
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0
            
CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 127.0.0.1
        port: 49001
        transport: tcp
    server2:
        ip: 127.0.0.1
        port: 49002
        transport: tcp
    server3:
        ip: 127.0.0.1
        port: 49003
        transport: tls

cetp_policy_file: config_cesb/cetp_policies.json
