# CES Configuration Parameters

CESIdentification:
    name: cesb
    domainId: cesb.demo.lte.
    certificate: config_cesb/cesb.crt
    private_key: config_cesb/cesb.key
    ca_certificate: config_cesb/ca.crt

DNS:
    soa: cesb.demo.lte.
    zonefile: db.cesb.demo.lte.
    server:
        loopback:
            ip: 127.0.0.1
            port: 54
    timeouts:
        naptr:
            - 0.010
            - 0.100
            - 0.200
        a:
            - 0.010
            - 0.100
            - 0.200
        aaaa:
            - 0.010
            - 0.100
            - 0.200
        any:
            - 0
            
CETPServers:
    serverNames:
        - server1
        - server2
        - server3
    server1:
        ip: 127.0.0.1
        port: 49001
        transport: tcp
    server2:
        ip: 127.0.0.1
        port: 49002
        transport: tcp
    server3:
        ip: 127.0.0.1
        port: 49003
        transport: tls

cetp_policy_file: config_cesb/cetp_policies.json